/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static pizza.EditPizza.model;
/**
 *
 * @author programmer
 */
public  class ViewPizza extends javax.swing.JPanel {

    /**
     * Creates new form ViewPizza
     */
     TableModel tmodel;
    JTable jTable;
    TableRowSorter<TableModel> rsorter;
    int i=0,k=0,l=0,p=0,y=0,j=0,y2=0,j2=0,y22=0,j22=0;
    Connection conn;
    Statement stm;
    ResultSet rs;
    String username="root";
    String password="";
    Count1 count=new Count1();
    int g=8+count.call3();
    Object array[][] = new Object[g][8];
    String columns[]={"Member id","Pizza id","Pizza Name","Quantity","Total Price","Address","Date","Time"};
    static Object[] row;
    static DefaultTableModel model;
    JScrollPane jScrollPane;
    String s1,sl1,sl2,sl3,sl4,sl5,sl6;
    EditPizza editPizza;
    public void gg(EditPizza ed){
              editPizza = ed;
    }
    public ViewPizza() {
        
        this.fillData();
       jTable = new javax.swing.JTable();

        
        jScrollPane = new JScrollPane();
        jScrollPane.setViewportView(jTable);
        model = new DefaultTableModel(array,columns);
        jTable.setModel(model);
       jTable.setSelectionBackground(new java.awt.Color(159, 25, 25));
        rsorter = new TableRowSorter<TableModel>(model);
		
		jTable.setRowSorter(rsorter);
       
			
        initComponents();
        this.add(jScrollPane,BorderLayout.CENTER);
        //add(jspane,BorderLayout.CENTER);
        
        //jTable1.setModel(model);
       jTable.addMouseListener(new MouseAdapter(){
           
           public void mouseClicked(MouseEvent e){
               int i = jTable.getSelectedRow();
               sl1 = model.getValueAt(i, 0).toString();
              ltf1.setText(sl1);
               System.out.println(sl1);
            
           }
       });
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        ltf1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(159, 25, 25));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(159, 25, 25));

        jButton1.setBackground(new java.awt.Color(159, 25, 25));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(159, 25, 25));
        jTextField1.setBorder(null);

        ltf1.setEditable(false);

        jButton2.setBackground(new java.awt.Color(159, 25, 25));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ltf1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ltf1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jButton1)
				{ 
				String text=jTextField1.getText();
					if(text.length()==0)
					{     rsorter.setRowFilter(null);  }
					rsorter.setRowFilter(RowFilter.regexFilter(text));
				}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         s1 = ltf1.getText();
      
        if(s1.isEmpty()){
            JOptionPane.showMessageDialog(this,"field is empty","Error",JOptionPane.ERROR_MESSAGE);
            
        }else{    
                    
        
                try{
							Class.forName("com.mysql.cj.jdbc.Driver");
							Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/avskpizza?useSSL = true",username,password);
      							String query = "delete from orders where id = ?";
      							PreparedStatement preparedStmt = con2.prepareStatement(query);
      							preparedStmt.setString(1, s1);
      							preparedStmt.execute();
                                                        JOptionPane.showMessageDialog(this,"Member("+s1+") all orders are deleted successful","Success",JOptionPane.INFORMATION_MESSAGE);
                                                        ltf1.setText("");	
                                                        int i2 = jTable.getSelectedRow();
                                                         model.removeRow(i2);
      							con2.close();
				   		} catch(ClassNotFoundException | HeadlessException | SQLException r){JOptionPane.showMessageDialog(this,r,"Error",JOptionPane.ERROR_MESSAGE);}
            
            }
    }//GEN-LAST:event_jButton2ActionPerformed

private void fillData(){
    
    try
			{
			
	
			Class.forName("com.mysql.cj.jdbc.Driver");
                        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/avskpizza?useSSL = true",username,password);
			stm= conn.createStatement(); 
			rs= stm.executeQuery("SELECT *  FROM orders ");	
			
			while(rs.next())
			{   
                            
				array[i++][0]=rs.getObject(1);
				array[k++][1]=rs.getObject(2);
				array[l++][2]=rs.getObject(3);
				array[p++][3]=rs.getObject(4);
				array[y++][4]=rs.getObject(5);
				array[j++][5]=rs.getObject(6);
                                array[y22++][6]=rs.getObject(7);
				array[j22++][7]=rs.getObject(8);
				

				
				
			}      
			conn.close();	
				
			}
		catch(SQLException |ClassNotFoundException e)
		{   	JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.INFORMATION_MESSAGE);
			 } 
    }

   
    public static void setRow(String s1,String s2,String s3,String s4,String s5,String s6){
            JLabel label = new JLabel();
					label.setIcon(new ImageIcon((s3)));
            row = new Object[6];
            row[0]=(Object)s1;
            row[1]=(Object)s2;
            row[2]=(Object)label;
            row[3]=(Object)s4;
            row[4]=(Object)s5;
            row[5]=(Object)s6;
            model.addRow(row);
          
            
            
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField ltf1;
    // End of variables declaration//GEN-END:variables
}
